// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitleAttribute("EFCore.FSharp")>]
[<assembly: AssemblyProductAttribute("EFCore.FSharp")>]
[<assembly: AssemblyVersionAttribute("10.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate", "2026-04-05T00:00:00.0000000+00:00")>]
[<assembly: AssemblyFileVersionAttribute("10.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("10.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel", "release")>]
[<assembly: AssemblyMetadataAttribute("GitHash", "68652cf")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "EFCore.FSharp"

    [<Literal>]
    let AssemblyProduct = "EFCore.FSharp"

    [<Literal>]
    let AssemblyVersion = "10.0.0"

    [<Literal>]
    let AssemblyMetadata_ReleaseDate = "2026-04-05T00:00:00.0000000+00:00"

    [<Literal>]
    let AssemblyFileVersion = "10.0.0"

    [<Literal>]
    let AssemblyInformationalVersion = "10.0.0"

    [<Literal>]
    let AssemblyMetadata_ReleaseChannel = "release"

    [<Literal>]
    let AssemblyMetadata_GitHash = "68652cf"
