// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitleAttribute("EFCore.FSharp")>]
[<assembly: AssemblyProductAttribute("EFCore.FSharp")>]
[<assembly: AssemblyVersionAttribute("6.0.7")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate", "2022-06-26T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("6.0.7")>]
[<assembly: AssemblyInformationalVersionAttribute("6.0.7")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel", "release")>]
[<assembly: AssemblyMetadataAttribute("GitHash", "bd06b49bb7290ad9a1242b35b07609a0299fdc04")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "EFCore.FSharp"

    [<Literal>]
    let AssemblyProduct = "EFCore.FSharp"

    [<Literal>]
    let AssemblyVersion = "6.0.7"

    [<Literal>]
    let AssemblyMetadata_ReleaseDate = "2022-06-26T00:00:00.0000000+01:00"

    [<Literal>]
    let AssemblyFileVersion = "6.0.7"

    [<Literal>]
    let AssemblyInformationalVersion = "6.0.7"

    [<Literal>]
    let AssemblyMetadata_ReleaseChannel = "release"

    [<Literal>]
    let AssemblyMetadata_GitHash = "bd06b49bb7290ad9a1242b35b07609a0299fdc04"
